<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
	pageEncoding="ISO-8859-1" import="com.cs336.pkg.*"%>
<%@ page import="java.io.*,java.util.*,java.sql.*"%>
<%@ page import="javax.servlet.http.*,javax.servlet.*"%>

<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
<title>Insert title here</title>
</head>
<body>
<%

		try {

			//Get the database connection
			ApplicationDB db = new ApplicationDB();	
			Connection con = db.getConnection();	
			
			String lID = request.getParameter("lid");
			
			Statement stmt = con.createStatement();
			//Make a SELECT query from the sells table with the price range specified by the 'price' parameter at the index.jsp
			String select = "SELECT lid, tNumber, t.fNumber, cid, name, seatNum, class, fare, purchaseDate, bookingFee FROM f_Tickets as t left join Flights as f on f.fNumber = t.fNumber where lid = ?;";

			PreparedStatement ps = con.prepareStatement(select);
			
			ps.setString(1, lID);
			
			ResultSet result = ps.executeQuery();

			
			//Make an HTML table to show the results in:
		if(result.next()) {
%>
		<h1>Total Revenue Generated by: <%=lID%></h1>
			
			<% String select2 = "SELECT lid, Count(*) as TicketsSold, sum(Fare+BookingFee) as TotalRevenue FROM f_Tickets as t left join Flights as f on f.fNumber = t.fNumber where lid = ?;";

			PreparedStatement ps2 = con.prepareStatement(select2);

			ps2.setString(1, lID);
			
			ResultSet result2 = ps2.executeQuery();
		
			result2.next();
			%>
		<em>Total Sales</em>
		<table border="1">
        <tr>
            <th>LID</th>
			<th>Tickets Bought</th>
            <th>Total Revenue</th>
        </tr>
	<% 
	out.println("<tr>");
	out.println("<td>" + result2.getString(1) + "</td>");
	out.println("<td>" + result2.getString(2) + "</td>"); 
	out.println("<td>" + result2.getString(3) + "</td>"); 
	
	out.println("</table>");
	%>
	<br></br>
	<em>Individual Sales</em>
	</table>
		<table border="1">
        <tr>
       		<th>LID</th>
            <th>Ticket</th>
            <th>Flight</th>
            <th>CID</th>
            <th>Name</th>
            <th>Seat Number</th>
            <th>Class</th>
            <th>Fare</th>
            <th>Purchase Date</th>
            <th>Booking Fee</th>
            
        </tr>
    
    <% 
    
    out.println("<tr>");
	
	out.println("<td>" + result.getString(1) + "</td>");
	out.println("<td>" + result.getString(2) + "</td>");
	out.println("<td>" + result.getString(3) + "</td>");
	out.println("<td>" + result.getString(4) + "</td>");
	out.println("<td>" + result.getString(5) + "</td>");
	out.println("<td>" + result.getString(6) + "</td>");
	out.println("<td>" + result.getString(7) + "</td>");
	out.println("<td>" + result.getString(8) + "</td>");
	out.println("<td>" + result.getString(9) + "</td>");
	out.println("<td>" + result.getString(10) + "</td>");
    
    		while(result.next()) {
		
    		out.println("<tr>");
    		
    		out.println("<td>" + result.getString(1) + "</td>");
    		out.println("<td>" + result.getString(2) + "</td>");
    		out.println("<td>" + result.getString(3) + "</td>");
    		out.println("<td>" + result.getString(4) + "</td>");
    		out.println("<td>" + result.getString(5) + "</td>");
    		out.println("<td>" + result.getString(6) + "</td>");
    		out.println("<td>" + result.getString(7) + "</td>");
    		out.println("<td>" + result.getString(8) + "</td>");
    		out.println("<td>" + result.getString(9) + "</td>");
    		out.println("<td>" + result.getString(10) + "</td>");
    		
    		out.println("</tr>");
		}
		out.println("</tbody>");
		out.println("</table>");
		}


		else{
	out.print("There is no revenue generated by: " + lID);
}
			//close the connection.
			con.close();

		} catch (Exception e) {
		}
	%>
</body>
</html>
